import {KEY,SANDBOX,emptyState,assess,validateState,mergeStates,safeSave} from './core.js?v=0.2.0';
import {DrawingEditor,renderDrawing} from './drawing.js?v=0.2.0';
import {SHEETS,hasDrawing} from './drawing-model.js?v=0.2.0';
import {GUIDES} from './teaching-guides.js?v=0.2.0';
const $=id=>document.getElementById(id);const now=()=>new Date().toISOString();
let state=emptyState(),expected=null,writable=true,currentDay=1,tickFrom=null,course,editor;
if(SANDBOX){document.querySelector('.notice').textContent='功能測試空間：測試紀錄與正式學習紀錄分開儲存。';document.querySelector('.version').textContent+=' · 功能測試';}
function storageMessage(msg,bad=false){$('storage-status').textContent=msg;$('storage-status').className=bad?'warning':'';}
try{expected=localStorage.getItem(KEY);if(expected)state=validateState(JSON.parse(expected));storageMessage('目前瀏覽器可用；尚無雲端備份。');}catch{writable=false;storageMessage('無法讀取原有儲存資料，已保留原資料並停止覆寫。新紀錄請立即匯出，勿清除瀏覽器資料。',true);}
function persist(){if(!writable)return false;try{expected=safeSave(localStorage,state,expected);storageMessage('已存至目前瀏覽器 · '+new Date().toLocaleTimeString('zh-TW')+' · 尚未同步雲端');return true;}catch(e){writable=false;storageMessage(e.message+' 儲存未完成，請先匯出本頁資料。',true);return false;}}
const blank=()=>({activeMs:0,reasoning:'',explanation:'',mistake:'',hint:0,answerViewed:false,errorType:'未判定',values:{},startedAt:'',updatedAt:now()});
function draft(){return state.drafts[currentDay]??=blank();}
function timeText(ms){const seconds=Math.floor(ms/1000);return `${String(Math.floor(seconds/60)).padStart(2,'0')}:${String(seconds%60).padStart(2,'0')}`;}
function elapsed(){return (state.drafts[currentDay]?.activeMs??0)+(tickFrom===null?0:Math.max(0,performance.now()-tickFrom));}
function bankTick(){if(tickFrom!==null){draft().activeMs+=Math.max(0,performance.now()-tickFrom);tickFrom=performance.now();draft().updatedAt=now();}}
function pause(){if(tickFrom===null)return;bankTick();tickFrom=null;$('timer-note').textContent='已暫停。按繼續計時才會累計時間。';$('start').disabled=false;$('pause').disabled=true;$('start').textContent='繼續計時';persist();paintStats();}
function capture(){const d=draft();for(const k of ['reasoning','explanation','mistake'])d[k]=$(k).value;d.hint=d.answerViewed?3:Number($('hint').value);$('hint').value=String(d.hint);d.errorType=$('error-type').value;document.querySelectorAll('[data-answer]').forEach(el=>d.values[el.dataset.answer]=el.value);d.drawing=editor?.get();d.updatedAt=now();return d;}
function textDoc(container,text){container.replaceChildren();for(const line of text.split('\n')){if(!line.trim())continue;let tag='p',value=line;const heading=line.match(/^#{1,4}\s+(.*)/);if(heading){tag='h3';value=heading[1];}else if(line.startsWith('---'))continue;const el=document.createElement(tag);el.textContent=value.replace(/\*\*/g,'');container.append(el);}}
function paintStats(){const days=new Set(state.records.map(r=>r.day));$('count').textContent=days.size;const ms=state.records.reduce((n,r)=>n+r.activeMs,0)+Object.values(state.drafts).reduce((n,d)=>n+d.activeMs,0);$('minutes').textContent=`累積 ${(ms/60000).toFixed(1)} 分鐘`;}
function showDay(day){pause();currentDay=day;localStorageSelection(day);$('day-select').value=String(day);const lesson=course.days[day-1],d=state.drafts[day]??blank();$('day-title').textContent=`D${String(day).padStart(2,'0')} · ${lesson.task}`;$('read-task').textContent=lesson.read;$('do-task').textContent=lesson.task;$('check-task').textContent=lesson.check;textDoc($('problem'),lesson.problem);$('beam-diagram').hidden=day!==1;$('answer-details').open=false;$('guide-details').open=false;const guide=GUIDES[day];textDoc($('guide-worked'),guide.worked.join('\n'));$('guide-plain').textContent=guide.plain;textDoc($('guide-draw'),guide.draw.join('\n'));$('numeric-fields').replaceChildren();for(const f of lesson.fields){const label=document.createElement('label');label.textContent=`${f.label}（${f.unit}）`;const input=document.createElement('input');input.type='text';input.inputMode='decimal';input.dataset.answer=f.id;input.setAttribute('aria-label',f.label);input.maxLength=100;input.value=d.values[f.id]??'';label.append(input);$('numeric-fields').append(label);}
 $('numeric-note').textContent=lesson.fields.length?'關鍵數值採相對誤差 1% 核對；欄位單位固定如標示。數值符合不代表推導已驗收。':'今天以觀念與推導練習為主，提交後標記待教練審閱。';for(const k of ['reasoning','explanation','mistake'])$(k).value=d[k];$('hint').value=String(d.hint);$('error-type').value=d.errorType;$('timer').textContent=timeText(d.activeMs);$('start').textContent=d.activeMs?'繼續計時':'開始計時';$('result').textContent='';editor?.set(d.drawing);}
function localStorageSelection(day){try{sessionStorage.setItem(SANDBOX?'learning-lab:sandbox:day':'learning-lab:day',String(day));}catch{}}
function showTab(name){document.querySelectorAll('.panel').forEach(el=>el.hidden=el.id!==name);document.querySelectorAll('[data-tab]').forEach(el=>el.classList.toggle('active',el.dataset.tab===name));if(name!=='today')pause();if(name==='history')renderHistory();if(name==='route')renderRoute();}
function renderRoute(){$('route-list').replaceChildren();for(const d of course.days){const row=document.createElement('article');row.className='route-row';const box=document.createElement('div'),title=document.createElement('strong'),p=document.createElement('p'),badge=document.createElement('span');title.textContent=`D${String(d.day).padStart(2,'0')} · ${d.task}`;p.textContent=d.check;badge.className='badge';badge.textContent=state.records.some(r=>r.day===d.day)?'已提交練習 · 尚待完整驗收':'尚未提交';box.append(title,p,badge);const button=document.createElement('button');button.className='secondary';button.textContent='開始這課';button.onclick=()=>{showDay(d.day);showTab('today');window.scrollTo({top:0,behavior:'smooth'});};row.append(box,button);$('route-list').append(row);}}
function renderHistory(){$('history-list').replaceChildren();if(!state.records.length){$('history-list').textContent='尚未提交練習。先完成一課，再回來看自己的進步。';return;}for(const r of [...state.records].sort((a,b)=>b.submittedAt.localeCompare(a.submittedAt))){const el=document.createElement('article');el.className='history-item';const h=document.createElement('h3');h.textContent=`D${String(r.day).padStart(2,'0')} · ${new Date(r.submittedAt).toLocaleString('zh-TW')}`;const info=document.createElement('p');info.textContent=`投入 ${(r.activeMs/60000).toFixed(1)} 分鐘 · 提示 ${r.hint} · ${r.errorType}`;const result=document.createElement('p');result.textContent=r.assessment.text;const pre=document.createElement('pre');pre.textContent=`數值：${Object.entries(r.values).map(([k,v])=>`${k}=${v}`).join('，')||'未填'}\n推導：${r.reasoning||'未填'}\n白話解釋：${r.explanation||'未填'}\n錯因／問題：${r.mistake||'未填'}`;const remove=document.createElement('button');remove.className='secondary';remove.textContent='刪除此筆紀錄';remove.onclick=()=>{if(!confirm('刪除這筆本機作答？建議先匯出備份；其他紀錄不受影響。'))return;state.records=state.records.filter(item=>item.id!==r.id);persist();paintStats();renderHistory();};el.append(h,info,result,pre);if(hasDrawing(r.drawing)){const note=document.createElement('p');note.textContent='圖解已保留；受力與變形圖尚待教練檢核。';el.append(note);for(const key of Object.keys(SHEETS)){if(!r.drawing.sheets[key].length)continue;const title=document.createElement('h4');title.textContent=SHEETS[key];el.append(title,renderDrawing(r.drawing,key));}}el.append(remove);$('history-list').append(el);}}
$('start').onclick=()=>{const d=draft();if(!d.startedAt)d.startedAt=now();tickFrom=performance.now();$('start').disabled=true;$('pause').disabled=false;$('timer-note').textContent='計時中。离開分頁會暫停；本次作答送出後結束這段計時。'.replace('离','離');persist();};$('pause').onclick=pause;
$('practice-form').addEventListener('input',()=>{capture();persist();});$('practice-form').addEventListener('change',()=>{capture();persist();});
for(const id of ['answer-details','guide-details'])$(id).addEventListener('toggle',()=>{if($(id).open){draft().answerViewed=true;$('hint').value='3';capture();persist();}});
$('practice-form').onsubmit=e=>{e.preventDefault();pause();const d=capture();if(!d.reasoning.trim()&&!d.explanation.trim()&&!Object.values(d.values).some(v=>v.trim())&&!hasDrawing(d.drawing)){$('result').textContent='請先畫圖或填寫答案、推導、白話解釋，再儲存作答。';return;}const hasNumeric=Object.values(d.values).some(v=>v.trim());const assessment=assess(hasNumeric?course.days[currentDay-1].fields:[],d.values,d.hint);if(hasDrawing(d.drawing))assessment.text='圖解已保留；'+assessment.text;const record={...structuredClone(d),id:crypto.randomUUID(),day:currentDay,submittedAt:now(),curriculumVersion:course.version,assessment};state.records.push(record);delete state.drafts[currentDay];const saved=persist();showDay(currentDay);$('result').textContent=(saved?'本次作答已存至瀏覽器。':'作答保留於本頁記憶體，請立即匯出備份。')+assessment.text;paintStats();};
document.querySelectorAll('[data-tab]').forEach(el=>el.onclick=()=>showTab(el.dataset.tab));$('day-select').onchange=e=>{capture();persist();showDay(Number(e.target.value));};
function download(value,name){const blob=new Blob([value],{type:'application/json;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
$('export').onclick=()=>{pause();const data={...state,exportedAt:now(),source:'learning-lab-browser-v0.2.0'};download(JSON.stringify(data,null,2),`learning-lab-${new Date().toISOString().slice(0,10)}.json`);$('export-status').textContent='已交給瀏覽器下載，請確認檔案確實保存。紀錄尚未同步雲端。';};
$('import').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>20*1024*1024)throw Error('檔案超過20MB。');pause();const incoming=validateState(JSON.parse(await file.text()));const merged=mergeStates(state,incoming);state=merged;const saved=persist();showDay(currentDay);paintStats();$('import-status').textContent=saved?`已合併，共${state.records.length}筆作答。`:'已載入本頁，瀏覽器儲存失敗，請匯出合併後備份。';}catch(err){$('import-status').textContent='未匯入：'+err.message;}e.target.value='';};
document.addEventListener('visibilitychange',()=>{if(document.hidden)pause();});window.addEventListener('pagehide',pause);window.addEventListener('storage',e=>{if(e.key===KEY&&e.newValue!==expected){writable=false;pause();storageMessage('另一個分頁已更新紀錄，本頁已停止覆寫。請匯出本頁資料，再重新整理合併。',true);}});
setInterval(()=>{$('timer').textContent=timeText(elapsed());},250);setInterval(()=>{if(tickFrom!==null){bankTick();persist();paintStats();}},5000);
editor=new DrawingEditor($('drawing-editor'),data=>{const d=draft();d.drawing=data;d.updatedAt=now();persist();});
try{const response=await fetch('curriculum.json'+new URL(import.meta.url).search);if(!response.ok)throw Error('教材讀取失敗');course=await response.json();for(const d of course.days){const option=document.createElement('option');option.value=String(d.day);option.textContent=`D${String(d.day).padStart(2,'0')} · ${d.task.slice(0,30)}`;$('day-select').append(option);}textDoc($('reference'),course.reference);textDoc($('answers'),course.answers);let savedDay=1;try{savedDay=Number(sessionStorage.getItem(SANDBOX?'learning-lab:sandbox:day':'learning-lab:day'))||1;}catch{}showDay(Math.min(30,Math.max(1,savedDay)));paintStats();}catch(e){$('day-title').textContent='教材尚未載入，請重新整理。';storageMessage(e.message,true);$('start').disabled=true;}
