import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';
import {resolveTopic,storageKey,dayKey} from '../site/topics.js';
import {emptyState,validateState,safeSave,mergeStates} from '../site/core.js';
import {emptyDrawing,shape} from '../site/drawing-model.js';
const rc='reinforced-concrete',sa='structural-analysis';
test('old links and storage keys remain unchanged; both topics and sandbox are isolated',()=>{assert.equal(resolveTopic(''),sa);assert.equal(resolveTopic('?topic=reinforced-concrete&v=0.3.0'),rc);assert.throws(()=>resolveTopic('?topic=unknown'));assert.equal(storageKey(sa),'learning-lab:v1');assert.equal(dayKey(sa),'learning-lab:day');assert.equal(storageKey(sa,true),'learning-lab:sandbox:v1');assert.equal(new Set([storageKey(sa),storageKey(rc),storageKey(sa,true),storageKey(rc,true)]).size,4);});
test('saving RC cannot overwrite legacy structural records; wrong-topic backups fail without mutation',()=>{const db=new Map(),storage={getItem:k=>db.get(k)??null,setItem:(k,v)=>db.set(k,v)};const a=emptyState(sa),b=emptyState(rc);const original=safeSave(storage,a,null);safeSave(storage,b,null);assert.equal(storage.getItem(storageKey(sa)),original);assert.equal(JSON.parse(storage.getItem(storageKey(rc))).topicId,rc);assert.throws(()=>validateState(a,rc),/主題不同/);assert.throws(()=>mergeStates(b,a),/主題不同/);assert.deepEqual(b,emptyState(rc));});
test('RC drawings, drafts, timers and submitted attempts round-trip and deduplicate',()=>{const drawing=emptyDrawing();drawing.sheets.force=[shape('line')];const d={activeMs:75000,reasoning:'RC test',explanation:'strain',mistake:'',hint:2,errorType:'方程',values:{},startedAt:'2026-09-15T12:00:00Z',updatedAt:'2026-09-15T12:01:15Z',drawing};const s=emptyState(rc);s.drafts[2]=d;s.records.push({...d,day:1,id:'rc-test',submittedAt:'2026-09-15T12:01:15Z',curriculumVersion:'rc-2026-09-v1',assessment:{text:'待審閱'}});const restored=validateState(JSON.parse(JSON.stringify(s)),rc);assert.deepEqual(restored,s);assert.deepEqual(mergeStates(s,restored),s);});
test('RC plan has 30 sequential tasks, honest review mode, diagnostic and official exam links',()=>{const data=JSON.parse(readFileSync(new URL('../site/rc-curriculum.json',import.meta.url)));assert.equal(data.topicId,rc);assert.equal(data.days.length,30);data.days.forEach((d,i)=>{assert.equal(d.day,i+1);for(const k of ['problem','task','read','check'])assert.ok(d[k].length>0);assert.deepEqual(d.fields,[]);assert.ok(d.guide.worked.length>=3);assert.ok(d.guide.plain.length>20);});assert.match(data.days[0].problem,/閉卷診斷/);assert.match(data.answers,/尚未提供30份逐題數值詳解/);assert.ok(data.sources.some(s=>s.url.includes('code=114180')));});
